package com.sai.oabs;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.web.servlet.ServletComponentScan;

//Automatically generated by the system
@ServletComponentScan
@SpringBootApplication
public class OabsApplication {

    public static void main(String[] args) {
        SpringApplication.run(OabsApplication.class, args);
    }

}
